/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e5e1e6",
        "surface-container-low": "#f2f3f8",
        "on-surface-variant": "#596067",
        "on-secondary-fixed-variant": "#5c5b5f",
        "primary": "#4f4ccd",
        "secondary-fixed-dim": "#d6d3d8",
        "inverse-surface": "#0c0e11",
        "on-tertiary-fixed": "#2f384f",
        "error": "#9e3f4e",
        "on-background": "#2d3339",
        "error-container": "#ff8b9a",
        "on-primary-fixed": "#2d27ad",
        "primary-fixed-dim": "#d2d0ff",
        "surface-tint": "#4f4ccd",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e4e8ef",
        "secondary-fixed": "#e5e1e6",
        "surface-container-highest": "#dde3eb",
        "secondary": "#605e62",
        "background": "#f9f9fc",
        "on-secondary-container": "#525155",
        "on-error": "#fff7f7",
        "tertiary-fixed": "#ced6f5",
        "inverse-primary": "#8382ff",
        "on-tertiary": "#f9f8ff",
        "on-secondary": "#fbf8fc",
        "outline": "#757b83",
        "surface-variant": "#dde3eb",
        "on-secondary-fixed": "#403f43",
        "inverse-on-surface": "#9c9da0",
        "outline-variant": "#acb3ba",
        "tertiary-dim": "#4a536b",
        "surface": "#f9f9fc",
        "primary-fixed": "#e2dfff",
        "on-surface": "#2d3339",
        "surface-dim": "#d3dbe4",
        "on-primary-fixed-variant": "#4c49c9",
        "surface-bright": "#f9f9fc",
        "tertiary": "#565f78",
        "secondary-dim": "#545256",
        "on-primary": "#faf6ff",
        "tertiary-fixed-dim": "#c0c9e6",
        "primary-dim": "#423fc0",
        "error-dim": "#4f0116",
        "on-primary-container": "#423ebf",
        "on-error-container": "#782232",
        "on-tertiary-container": "#424a63",
        "surface-container": "#ebeef4",
        "on-tertiary-fixed-variant": "#4b546d",
        "primary-container": "#e2dfff",
        "tertiary-container": "#ced6f5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
